### ISSUE TITLE
Is it only for users? 

### ISSUE THREAD

**Issue by zzm88** [byteweaver/django-tickets#2]
I don't see urls for admin to reply to users about the tickets.

**Comment by noxan** [comment]
You can reply to tickets using the inline admin if you click on any ticket. See screenshot below. Hope this answers your question.

<img width="1182" alt="Screen Shot 2020-04-20 at 5 55 37 PM" src="https://user-images.githubusercontent.com/536225/79772302-36d7c280-8330-11ea-8625-627895e59208.png">

**Comment by noxan** [comment]
Please reopen if the issue should not be resolved, thanks!
